spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        decode404: false

weather:
  api-key: 65c4c2723f2b02bda34d9640cdf44cbd
  url: http://api.openweathermap.org/data/2.5/weather